from enum import Enum


class IntentLabel(str, Enum):
    FACT = "FACT"
    SUMMARY = "SUMMARY"
    COMPARISON = "COMPARISON"
    NAVIGATION = "NAVIGATION"
    METHOD_CONTEXT = "METHOD_CONTEXT"
    LIMITATION = "LIMITATION"
    UNKNOWN = "UNKNOWN"
